### ISSUE TITLE
Make same project for publishing widgets in notification bar

### ISSUE THREAD

**Issue by vitalii17** [djbozkosz/Symbian-HomeScreen-Widget-QML#1]
I am working on Telegram for Symbian. I want to create widget for home screen and widget  for notification bar (like as standard messages). I cant find library for this. I know that are not available public API for this, but you can make same hacks with dll's such as in this project.

**Comment by djbozkosz** [comment]
Hi,
I'm sorry but I don't have clue how to do this :(

**Comment by djbozkosz** [comment]
Hello,
I successfully found solution how to add custom notification into notification center. Later, I'll make an app and simple public api around. To keep this for universal usage.

Screen from N8:
![scr_272](https://user-images.githubusercontent.com/5783189/48863092-81b27b00-edc8-11e8-88f1-8e360bff20c9.jpg)

**Comment by vitalii17** [comment]
Hello,
Good news! Thank you for you work. I will use this API in my apps.

**Comment by djbozkosz** [comment]
One small issue is that phone must be rooted to use custom notifications. Internally there must be implemented ECOM plugin which has to have ECOM capabilities = all capabilities without TBC. If no or necessary capabilities are used then plugin doesn't work.

**Comment by djbozkosz** [comment]
Currently, I'm thinking about API something like this:

```cpp
// types

struct Activity
{
	string Title;
	string SubTitle;
	string IconPath;
	bool   OpenAppOnTap;
	string UserData;
};

struct Notification : public Activity
{
	uint   StatusIcon;
	string AudioPath;
	bool   Vibrate;
	bool   UseLight;
	bool   UsePopup;
	bool   UseDialog;
	bool   UseNotification;
	uint   SecondsFromNow;
};

// notifications

uint ScheduleNotification(const Notification& notification)
{
	// return notificationID
}

bool CancelNotification(uint notificationID)
{
	// true on success
}

uint ClearNotificationCenter()
{
	// number of removed notifications
}

// activities

uint AddOrUpdateActivity(const Activity& activity, uint activityID = 0)
{
	// return activityID
}

bool RemoveActivity(uint activityID)
{
	// true on success
}
```

Activities remains on tap, notifications are consumed.

**Comment by djbozkosz** [comment]
Unfortunately on my N8 with Belle Refresh I see all items as notifications. There aren't activities. But currently I don't care about this.

Also, I would like to do some simple settings app accessible from settings with similar functionality you have on Android or iOS.

**Comment by djbozkosz** [comment]
Another thing is implement Firebase Messaging service to support push notifications ;)

**Comment by vitalii17** [comment]
It is a very important work. 6 years have passed since Nokia dropped development of Symbian, but now there are big community of users.

I will update my apps to use this notification library and I will use notifications in apps that will be developed.

I will test this library on Symbian Belle FP2.

**Comment by djbozkosz** [comment]
Ok, so I'm currently working on notification center app. Basic functionality will be:
- set of predefined items (like weather, battery, etc...) - can be hidden
- possibility of scheduling notications (or just activity item) for 3rd party apps via api - something like in the snippet above

There are some examples with dummy icons.

![Scr_293](https://user-images.githubusercontent.com/5783189/55109323-deef6d80-50d5-11e9-8a3b-ee90097c4306.jpg)
![Scr_294](https://user-images.githubusercontent.com/5783189/55109324-deef6d80-50d5-11e9-8d3b-9f5b995df65c.jpg)

In first two items imagine the grayscaled app icon with number in badge.
The last one could be state item with data counter icon and probably optional current weather.

![Scr_295](https://user-images.githubusercontent.com/5783189/55109325-deef6d80-50d5-11e9-88dd-6b126e94b696.jpg)

Suggestions wanted ;)

**Comment by vitalii17** [comment]
Excellent! Thank you for this work. Do you have a product - ready code?

**Comment by djbozkosz** [comment]
Currently, I'm working on it one month and I guess I will work on in next month, at least. Then I hope, I will have some beta state of notification center app that could be published. This first version should include some in-build notifications like weater, battery, notification settings app and support for developers.

This support could be some static library linked into app which communicates with notification service and provides api for scheduling notifications, checking permissions and so on.

**Comment by djbozkosz** [comment]
Working example of notification badges:

![Scr_306](https://user-images.githubusercontent.com/5783189/55669721-0fc06700-587b-11e9-8ecf-8ce167d3f7dd.jpg)

Developer just provides the icon mask. Styling is done by notification service.

**Comment by djbozkosz** [comment]
App released: [https://applist.schumi1331.de/content/214](https://applist.schumi1331.de/content/214)
Example here: [https://github.com/djbozkosz/Symbian-NotificationCenter-Example](https://github.com/djbozkosz/Symbian-NotificationCenter-Example)
